### ISSUE TITLE
graveyard of shame

### ISSUE THREAD

**Issue by Wagenosrs** [MathieuDR/orsr-discord-automator#13]
i want a automatic graveyard of shame channel, the idea as following:
- who died a command !shame@wagen (discord tag)
- where he died (location boss)
- any member can use the channel
- screenshot of the person
- a personal command for personal score
- a command for the total deaths
- last time a personal death (not necessary) we could scroll up.

thanks already for looking into it!

**Comment by MathieuDR** [comment]
Location & boss type optional, or required?

**Comment by Wagenosrs** [comment]
not required, the photo will reveal it :)

**Comment by MathieuDR** [comment]
### Development progress

- [ ] Command 
  - [x] Definitions
  - [x] Requests
  - [ ] Handlers
    - [ ] Authorization
    - [x] Options
    - [x] Service calls
    - [ ] Presentation
      - [ ] Leaderboard
      - [ ] Shames
- [ ] Service layer
   - [x] DefinItions
   - [ ] Authorization
   - [ ] Business logic
     - [ ] Opting in
- [ ] Repository & data
  - [x] Models
  - [x] Definitions
  - [ ] Implementation
