### ISSUE TITLE
Feature: Clan funds tracker

### ISSUE THREAD

**Issue by Fencko** [MathieuDR/orsr-discord-automator#2]
what i want is a clanpot bot wich can automaticly calculate who donated how much and how much is left in the clanpot

so me (or any staff member) put in +50M @user

then the bot should output in #clanpot "@user donated 50M, The Clanpot is now on 50M"
here it also should be able to -50M for prize money and it would deduct 50M of the clanpot and show its new total.

and it should output in another channel; #donatie-ranking the ranking of the user, so said being 50M is the third most donated the user should be at spot #3, this should be updated automaticly aswell with each new donation.

**Comment by MathieuDR** [comment]
To summarize the following need to be implemented

- Ranking from 'donations'
- Currency tracker
- Output on all changes
